const alumniData = [
  {
    id: 1,
    name: "Jordan Mitchell",
    major: "Computer Science",
    gradYear: 2018,
    position: "Software Engineer",
    company: "Google",
    city: "Mountain View, CA",
    lat: 37.3861,
    lng: -122.0839,
    career: "Technology",
    bio: "Building developer tools at Google. Happy to chat about breaking into big tech.",
    avatar: "JM"
  },
  {
    id: 2,
    name: "Alexis Carter",
    major: "Business Administration",
    gradYear: 2015,
    position: "VP of Finance",
    company: "JPMorgan Chase",
    city: "New York, NY",
    lat: 40.7128,
    lng: -74.0060,
    career: "Finance & Banking",
    bio: "10+ years in investment banking. Passionate about financial literacy in the Black community.",
    avatar: "AC"
  },
  {
    id: 3,
    name: "Marcus Thompson",
    major: "Communications",
    gradYear: 2020,
    position: "Broadcast Journalist",
    company: "CNN",
    city: "Atlanta, GA",
    lat: 33.7490,
    lng: -84.3880,
    career: "Media & Entertainment",
    bio: "Covering national politics and social justice at CNN. Hampton shaped my voice.",
    avatar: "MT"
  },
  {
    id: 4,
    name: "Simone Reeves",
    major: "Nursing",
    gradYear: 2022,
    position: "Registered Nurse",
    company: "Johns Hopkins Hospital",
    city: "Baltimore, MD",
    lat: 39.2904,
    lng: -76.6122,
    career: "Healthcare",
    bio: "Critical care RN. Advocate for health equity and diversity in medicine.",
    avatar: "SR"
  },
  {
    id: 5,
    name: "Darius Evans",
    major: "Engineering",
    gradYear: 2010,
    position: "Senior Aerospace Engineer",
    company: "NASA",
    city: "Houston, TX",
    lat: 29.7604,
    lng: -95.3698,
    career: "Engineering & Architecture",
    bio: "Working on spacecraft propulsion systems. STEM is for everyone.",
    avatar: "DE"
  },
  {
    id: 6,
    name: "Imani Washington",
    major: "Political Science",
    gradYear: 2005,
    position: "Policy Director",
    company: "U.S. House of Representatives",
    city: "Washington, DC",
    lat: 38.9072,
    lng: -77.0369,
    career: "Government & Policy",
    bio: "Shaping education and housing policy on Capitol Hill. Public service is a calling.",
    avatar: "IW"
  },
  {
    id: 7,
    name: "Naomi Foster",
    major: "Architecture",
    gradYear: 2018,
    position: "Urban Design Lead",
    company: "Skidmore, Owings & Merrill",
    city: "Chicago, IL",
    lat: 41.8781,
    lng: -87.6298,
    career: "Engineering & Architecture",
    bio: "Designing equitable urban spaces. HU taught me that architecture is a social art.",
    avatar: "NF"
  },
  {
    id: 8,
    name: "Khalil Booker",
    major: "Biology",
    gradYear: 2024,
    position: "Research Associate",
    company: "Pfizer",
    city: "New York, NY",
    lat: 40.7589,
    lng: -73.9851,
    career: "Healthcare",
    bio: "Fresh Hampton grad working in biotech. Love connecting with current students!",
    avatar: "KB"
  },
  {
    id: 9,
    name: "Tiara Jenkins",
    major: "Computer Science",
    gradYear: 2022,
    position: "Product Manager",
    company: "Spotify",
    city: "New York, NY",
    lat: 40.6892,
    lng: -74.0445,
    career: "Technology",
    bio: "PM on Spotify's creator platform. CS + creativity = endless possibilities.",
    avatar: "TJ"
  },
  {
    id: 10,
    name: "Raymond Cole",
    major: "Business Administration",
    gradYear: 2010,
    position: "Founder & CEO",
    company: "Cole Ventures",
    city: "Los Angeles, CA",
    lat: 34.0522,
    lng: -118.2437,
    career: "Entrepreneurship",
    bio: "Serial entrepreneur. Built 3 companies from the ground up. Happy to mentor aspiring founders.",
    avatar: "RC"
  },
  {
    id: 11,
    name: "Brianna Hall",
    major: "Communications",
    gradYear: 2015,
    position: "Marketing Director",
    company: "Nike",
    city: "Portland, OR",
    lat: 45.5051,
    lng: -122.6750,
    career: "Media & Entertainment",
    bio: "Leading brand storytelling at Nike. Hampton's communications program was world class.",
    avatar: "BH"
  },
  {
    id: 12,
    name: "Victor Okafor",
    major: "Engineering",
    gradYear: 2020,
    position: "Electrical Engineer",
    company: "Tesla",
    city: "Austin, TX",
    lat: 30.2672,
    lng: -97.7431,
    career: "Technology",
    bio: "Working on EV battery systems at Tesla. HBCUs produce world-class engineers.",
    avatar: "VO"
  }
];
